version: '3.9'

services:
  backend:
    container_name: nutricookiebook-backend
    build: ./backend
    ports:
      - '5000:5000'
    environment:
      - DATABASE_URL=postgresql://postgres:1234@db/nutricookiebook
    command: bash -c "alembic upgrade head && uvicorn main:app --host 0.0.0.0 --port 5000"
    depends_on:
      db:
        condition: service_healthy

  frontend:
      container_name: nutricookiebook-frontend
      build: ./frontend
      ports:
        - '3000:3000'
      environment:
        - REACT_APP_ENDPOINT=http://127.0.0.1:5000
      command: "npm start"
      depends_on:
        - backend

  db:
      container_name: nutricookiebook-db
      build: ./db
      volumes:
        - /docker-entrypoint-initdb.d
      environment:
        POSTGRES_PASSWORD: 1234
        POSTGRES_USER: postgres
      healthcheck:
        test: ["CMD-SHELL", "pg_isready -U postgres"]
        interval: 5s
        timeout: 5s
        retries: 10
      