"""add columns to existing tables

Revision ID: 27f0621c679c
Revises: c650b036a77d
Create Date: 2023-12-26 14:46:37.586907

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27f0621c679c'
down_revision: Union[str, None] = 'c650b036a77d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('author_id', sa.String(), nullable=True), schema='public')
    op.create_index('ix_products_author_id', 'products', ['author_id'], unique=False, schema='public')
    op.create_foreign_key(None, 'products', 'users', ['author_id'], ['id'], source_schema='public', referent_schema='public')

    op.add_column('primary_ingredients', sa.Column('author_id', sa.String(), nullable=True), schema='main')
    op.create_index('ix_primary_ingredients_author_id', 'primary_ingredients', ['author_id'], unique=False, schema='main')
    op.create_foreign_key(None, 'primary_ingredients', 'users', ['author_id'], ['id'], source_schema='main', referent_schema='public')

    op.add_column('reference_ingredients', sa.Column('author_id', sa.String(), nullable=True), schema='main')
    op.create_index('ix_reference_ingredients_author_id', 'reference_ingredients', ['author_id'], unique=False, schema='main')
    op.create_foreign_key(None, 'reference_ingredients', 'users', ['author_id'], ['id'], source_schema='main', referent_schema='public')

    op.add_column('product_nutrients', sa.Column('author_id', sa.String(), nullable=True), schema='public')
    op.create_index('ix_product_nutrients_author_id', 'product_nutrients', ['author_id'], unique=False, schema='public')
    op.create_foreign_key(None, 'product_nutrients', 'users', ['author_id'], ['id'], source_schema='public', referent_schema='public')

    op.add_column('nutrients', sa.Column('unit', sa.String(), nullable=True), schema='public')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_products_author_id', table_name='products', schema='public')
    op.drop_column('products', 'author_id', schema='public')

    op.drop_index('ix_primary_ingredients_author_id', table_name='primary_ingredients', schema='main')
    op.drop_column('primary_ingredients', 'author_id', schema='main')

    op.drop_index('ix_reference_ingredients_author_id', table_name='reference_ingredients', schema='main')
    op.drop_column('reference_ingredients', 'author_id', schema='main')

    op.drop_index('ix_product_nutrients_author_id', table_name='product_nutrients', schema='public')
    op.drop_column('product_nutrients', 'author_id', schema='public')

    op.drop_column('nutrients', 'unit', schema='public')
    # ### end Alembic commands ###
