"""update nutrients by units

Revision ID: 55c6aaa7a645
Revises: 27f0621c679c
Create Date: 2023-12-26 16:39:18.148176

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55c6aaa7a645'
down_revision: Union[str, None] = '27f0621c679c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with open(f"./alembic/scripts/update-public-nutrients-by-units.sql", "r", encoding="utf-8") as f:
        query = f.read()
    query = query.replace("\n", "")
    op.execute(query)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
