"""fill main tables with data

Revision ID: 571aa3aa04ed
Revises: f43b2b98c3c2
Create Date: 2023-11-05 02:10:00.034974

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '571aa3aa04ed'
down_revision: Union[str, None] = 'f43b2b98c3c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    files = [
        "main-recipe-dish-preparation-methods-reference",
        "main-recipe-dish-tags-reference",
        "main-recipe-dish-units-reference",
        "main-ingredients",
        "main-recipes",
        "main-recipe-ingredients",
        "main-primary-ingredients",
        "main-reference-ingredients",
        "main-mapped-ingredient-values",
        "main-deleted-mapped-values",
        "main-mapping-logs",
        "main-tagged-ingredient-statuses",
        "main-tagged-ingredient-values"
    ]

    for file in files:
        with open(f"./alembic/scripts/{file}.sql", "r", encoding="utf-8") as f:
            query = f.read()
        query = query.replace("\n", "")
        op.execute(query)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
