"""create mapping/tagging history tables

Revision ID: c650b036a77d
Revises: 571aa3aa04ed
Create Date: 2023-11-19 00:11:03.872855

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c650b036a77d'
down_revision: Union[str, None] = '571aa3aa04ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mapping_history',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('page', sa.Integer(), nullable=False),
    sa.Column('letter', sa.String(), nullable=False),
    sa.Column('author_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['public.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='main'
    )
    op.create_index('ix_mapping_history_author_id', 'mapping_history', ['author_id'], unique=False, schema='main')
    op.create_table('tagging_history',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('page', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['public.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='main'
    )
    op.create_index('ix_tagging_history_author_id', 'tagging_history', ['author_id'], unique=False, schema='main')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_tagging_history_author_id', table_name='tagging_history', schema='main')
    op.drop_table('tagging_history', schema='main')
    op.drop_index('ix_mapping_history_author_id', table_name='mapping_history', schema='main')
    op.drop_table('mapping_history', schema='main')
    # ### end Alembic commands ###
