"""create db tables

Revision ID: cc674899ad1a
Revises: 
Create Date: 2023-11-05 01:48:52.459210

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc674899ad1a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('consultants',
    sa.Column('id', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='main'
    )
    op.create_index('ix_consultants_id', 'consultants', ['id'], unique=True, schema='main')
    op.create_table('files',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('path', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('sha256hash', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='main'
    )
    op.create_table('primary_ingredients',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='main'
    )
    op.create_index('ix_primary_ingredients_name', 'primary_ingredients', ['name'], unique=True, schema='main')
    op.create_table('recipe_dish_preparation_methods_reference',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='main'
    )
    op.create_index('ix_recipe_dish_preparation_methods_reference_name', 'recipe_dish_preparation_methods_reference', ['name'], unique=True, schema='main')
    op.create_table('recipe_dish_tags_reference',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='main'
    )
    op.create_index('ix_recipe_dish_tags_reference_name', 'recipe_dish_tags_reference', ['name'], unique=True, schema='main')
    op.create_table('recipe_dish_units_reference',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='main'
    )
    op.create_index('ix_recipe_dish_units_reference_name_type', 'recipe_dish_units_reference', ['name', 'type'], unique=True, schema='main')
    op.create_table('recipe_list_categories',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('color', sa.String(), nullable=False),
    sa.Column('preview_url', sa.String(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='main'
    )
    op.create_table('ingredients',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('price', sa.Numeric(), nullable=False),
    sa.Column('preview_url', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_table('nutrient_list_headers',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('displayed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_table('parsing_themes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('first_category', sa.String(), nullable=False),
    sa.Column('second_category', sa.String(), nullable=False),
    sa.Column('connection', sa.String(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_index('ix_parsing_themes_filename', 'parsing_themes', ['filename'], unique=True, schema='public')
    op.create_index('ix_parsing_themes_first_category_second_category', 'parsing_themes', ['first_category', 'second_category'], unique=True, schema='public')
    op.create_table('product_list_categories',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_table('recipes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('method', sa.String(), nullable=True),
    sa.Column('preview_url', sa.String(), nullable=True),
    sa.Column('tags', sa.ARRAY(sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_table('tags_reference',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_table('user_types_reference',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_index('ix_user_types_reference_type', 'user_types_reference', ['type'], unique=True, schema='public')
    op.create_table('ingredients',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('consultant_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['consultant_id'], ['main.consultants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='main'
    )
    op.create_index('ix_ingredients_consultant_id', 'ingredients', ['consultant_id'], unique=False, schema='main')
    op.create_index('ix_ingredients_name_consultant_id', 'ingredients', ['name', 'consultant_id'], unique=True, schema='main')
    op.create_table('recipes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('method_id', sa.String(), nullable=False),
    sa.Column('preview_url', sa.String(), nullable=True),
    sa.Column('photo_file_id', sa.String(), nullable=True),
    sa.Column('consultant_id', sa.String(), nullable=True),
    sa.Column('volume', sa.Numeric(), nullable=False),
    sa.Column('unit_volume_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['consultant_id'], ['main.consultants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['method_id'], ['main.recipe_dish_preparation_methods_reference.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['photo_file_id'], ['main.files.id'], ),
    sa.ForeignKeyConstraint(['unit_volume_id'], ['main.recipe_dish_units_reference.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='main'
    )
    op.create_index('ix_recipes_consultant_id', 'recipes', ['consultant_id'], unique=False, schema='main')
    op.create_index('ix_recipes_method_id', 'recipes', ['method_id'], unique=False, schema='main')
    op.create_index('ix_recipes_photo_file_id', 'recipes', ['photo_file_id'], unique=False, schema='main')
    op.create_index('ix_recipes_unit_volume_id', 'recipes', ['unit_volume_id'], unique=False, schema='main')
    op.create_table('tagged_ingredient_values',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('ingredient_id', sa.String(), nullable=False),
    sa.Column('tag_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['ingredient_id'], ['main.primary_ingredients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['main.recipe_dish_tags_reference.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='main'
    )
    op.create_index('ix_tagged_ingredient_values_ingredient_id', 'tagged_ingredient_values', ['ingredient_id'], unique=False, schema='main')
    op.create_index('ix_tagged_ingredient_values_tag_id', 'tagged_ingredient_values', ['tag_id'], unique=False, schema='main')
    op.create_table('nutrients',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('header_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['header_id'], ['public.nutrient_list_headers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_index('ix_nutrients_header_id', 'nutrients', ['header_id'], unique=False, schema='public')
    op.create_table('products',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('category_id', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('link', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['public.product_list_categories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_index('ix_products_category_id', 'products', ['category_id'], unique=False, schema='public')
    op.create_table('recipe_ingredients',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('ingredient_id', sa.String(), nullable=True),
    sa.Column('recipe_id', sa.String(), nullable=True),
    sa.Column('amount', sa.String(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('property', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['ingredient_id'], ['public.ingredients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recipe_id'], ['public.recipes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_index('ix_recipe_ingredients_ingredient_id', 'recipe_ingredients', ['ingredient_id'], unique=False, schema='public')
    op.create_index('ix_recipe_ingredients_recipe_id', 'recipe_ingredients', ['recipe_id'], unique=False, schema='public')
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('login', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('type_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['type_id'], ['public.user_types_reference.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_index('ix_users_login', 'users', ['login'], unique=True, schema='public')
    op.create_index('ix_users_type_id', 'users', ['type_id'], unique=False, schema='public')
    op.create_table('mapped_ingredient_values',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('ingredient_id', sa.String(), nullable=False),
    sa.Column('primary_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('author_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('controller_id', sa.String(), nullable=True),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['public.users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ingredient_id'], ['main.ingredients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['primary_id'], ['main.primary_ingredients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='main'
    )
    op.create_index('ix_mapped_ingredient_values_author_id', 'mapped_ingredient_values', ['author_id'], unique=False, schema='main')
    op.create_index('ix_mapped_ingredient_values_ingredient_id', 'mapped_ingredient_values', ['ingredient_id'], unique=False, schema='main')
    op.create_index('ix_mapped_ingredient_values_primary_id', 'mapped_ingredient_values', ['primary_id'], unique=False, schema='main')
    op.create_table('deleted_mapped_values',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('ingredient_id', sa.String(), nullable=False),
    sa.Column('primary_id', sa.String(), nullable=False),
    sa.Column('author_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['public.users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ingredient_id'], ['main.ingredients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['primary_id'], ['main.primary_ingredients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='main'
    )
    op.create_index('ix_deleted_mapped_values_author_id', 'deleted_mapped_values', ['author_id'], unique=False, schema='main')
    op.create_index('ix_deleted_mapped_values_ingredient_id', 'deleted_mapped_values', ['ingredient_id'], unique=False, schema='main')
    op.create_index('ix_deleted_mapped_values_primary_id', 'deleted_mapped_values', ['primary_id'], unique=False, schema='main')
    op.create_table('mapping_logs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('ingredient_id', sa.String(), nullable=False),
    sa.Column('log', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['ingredient_id'], ['main.ingredients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='main'
    )
    op.create_index('ix_mapping_logs_ingredient_id', 'mapping_logs', ['ingredient_id'], unique=False, schema='main')
    op.create_table('recipe_categories',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('categories_id', sa.String(), nullable=False),
    sa.Column('recipe_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['categories_id'], ['main.recipe_list_categories.id'], ),
    sa.ForeignKeyConstraint(['recipe_id'], ['main.recipes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='main'
    )
    op.create_index('ix_recipe_categories_categories_id', 'recipe_categories', ['categories_id'], unique=False, schema='main')
    op.create_index('ix_recipe_categories_recipe_id', 'recipe_categories', ['recipe_id'], unique=False, schema='main')
    op.create_table('recipe_ingredients',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('ingredient_id', sa.String(), nullable=False),
    sa.Column('recipe_id', sa.String(), nullable=False),
    sa.Column('volume', sa.Numeric(), nullable=False),
    sa.Column('unit_volume_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['ingredient_id'], ['main.ingredients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recipe_id'], ['main.recipes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['unit_volume_id'], ['main.recipe_dish_units_reference.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='main'
    )
    op.create_index('ix_recipe_ingredients_ingredient_id_recipe_id', 'recipe_ingredients', ['ingredient_id', 'recipe_id'], unique=True, schema='main')
    op.create_index('ix_recipe_ingredients_recipe_id', 'recipe_ingredients', ['recipe_id'], unique=False, schema='main')
    op.create_index('ix_recipe_ingredients_unit_volume_id', 'recipe_ingredients', ['unit_volume_id'], unique=False, schema='main')
    op.create_table('recipe_tags',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('recipe_id', sa.String(), nullable=False),
    sa.Column('dish_tag_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['dish_tag_id'], ['main.recipe_dish_tags_reference.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recipe_id'], ['main.recipes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='main'
    )
    op.create_index('ix_recipe_tags_dish_tag_id', 'recipe_tags', ['dish_tag_id'], unique=False, schema='main')
    op.create_index('ix_recipe_tags_recipe_id_dish_tag_id', 'recipe_tags', ['recipe_id', 'dish_tag_id'], unique=True, schema='main')
    op.create_table('reference_ingredients',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('reference_id', sa.String(), nullable=False),
    sa.Column('primary_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['primary_id'], ['main.primary_ingredients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reference_id'], ['public.products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='main'
    )
    op.create_index('ix_reference_ingredients_primary_id', 'reference_ingredients', ['primary_id'], unique=False, schema='main')
    op.create_index('ix_reference_ingredients_reference_id', 'reference_ingredients', ['reference_id'], unique=False, schema='main')
    op.create_table('tagged_ingredient_statuses',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('ingredient_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('author_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('controller_id', sa.String(), nullable=True),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['public.users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ingredient_id'], ['main.primary_ingredients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='main'
    )
    op.create_index('ix_tagged_ingredient_statuses_author_id', 'tagged_ingredient_statuses', ['author_id'], unique=False, schema='main')
    op.create_index('ix_tagged_ingredient_statuses_ingredient_id', 'tagged_ingredient_statuses', ['ingredient_id'], unique=False, schema='main')
    op.create_table('parsing_sessions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['public.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_index('ix_parsing_sessions_filename', 'parsing_sessions', ['filename'], unique=True, schema='public')
    op.create_index('ix_parsing_sessions_user_id', 'parsing_sessions', ['user_id'], unique=False, schema='public')
    op.create_table('product_nutrients',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('product_id', sa.String(), nullable=False),
    sa.Column('nutrient_id', sa.String(), nullable=False),
    sa.Column('amount', sa.Numeric(), nullable=True),
    sa.Column('unit', sa.String(), nullable=True),
    sa.Column('rsp_percent', sa.Numeric(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['nutrient_id'], ['public.nutrients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['public.products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_index('ix_product_nutrients_nutrient_id', 'product_nutrients', ['nutrient_id'], unique=False, schema='public')
    op.create_index('ix_product_nutrients_product_id', 'product_nutrients', ['product_id'], unique=False, schema='public')
    op.create_table('products_ingredients',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('product_id', sa.String(), nullable=False),
    sa.Column('ingredient_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['ingredient_id'], ['public.ingredients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['public.products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_index('ix_products_ingredients_product_id', 'products_ingredients', ['product_id'], unique=False, schema='public')
    op.create_index('x_products_ingredients_ingredient_id', 'products_ingredients', ['ingredient_id'], unique=False, schema='public')
    op.create_table('tags_products',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tag_id', sa.String(), nullable=False),
    sa.Column('product_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['public.products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['public.tags_reference.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_index('ix_tags_products_product_id', 'tags_products', ['product_id'], unique=False, schema='public')
    op.create_index('ix_tags_products_tag_id', 'tags_products', ['tag_id'], unique=False, schema='public')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_tags_products_tag_id', table_name='tags_products', schema='public')
    op.drop_index('ix_tags_products_product_id', table_name='tags_products', schema='public')
    op.drop_table('tags_products', schema='public')
    op.drop_index('x_products_ingredients_ingredient_id', table_name='products_ingredients', schema='public')
    op.drop_index('ix_products_ingredients_product_id', table_name='products_ingredients', schema='public')
    op.drop_table('products_ingredients', schema='public')
    op.drop_index('ix_product_nutrients_product_id', table_name='product_nutrients', schema='public')
    op.drop_index('ix_product_nutrients_nutrient_id', table_name='product_nutrients', schema='public')
    op.drop_table('product_nutrients', schema='public')
    op.drop_index('ix_parsing_sessions_user_id', table_name='parsing_sessions', schema='public')
    op.drop_index('ix_parsing_sessions_filename', table_name='parsing_sessions', schema='public')
    op.drop_table('parsing_sessions', schema='public')
    op.drop_index('ix_tagged_ingredient_statuses_ingredient_id', table_name='tagged_ingredient_statuses', schema='main')
    op.drop_index('ix_tagged_ingredient_statuses_author_id', table_name='tagged_ingredient_statuses', schema='main')
    op.drop_table('tagged_ingredient_statuses', schema='main')
    op.drop_index('ix_reference_ingredients_reference_id', table_name='reference_ingredients', schema='main')
    op.drop_index('ix_reference_ingredients_primary_id', table_name='reference_ingredients', schema='main')
    op.drop_table('reference_ingredients', schema='main')
    op.drop_index('ix_recipe_tags_recipe_id_dish_tag_id', table_name='recipe_tags', schema='main')
    op.drop_index('ix_recipe_tags_dish_tag_id', table_name='recipe_tags', schema='main')
    op.drop_table('recipe_tags', schema='main')
    op.drop_index('ix_recipe_ingredients_unit_volume_id', table_name='recipe_ingredients', schema='main')
    op.drop_index('ix_recipe_ingredients_recipe_id', table_name='recipe_ingredients', schema='main')
    op.drop_index('ix_recipe_ingredients_ingredient_id_recipe_id', table_name='recipe_ingredients', schema='main')
    op.drop_table('recipe_ingredients', schema='main')
    op.drop_index('ix_recipe_categories_recipe_id', table_name='recipe_categories', schema='main')
    op.drop_index('ix_recipe_categories_categories_id', table_name='recipe_categories', schema='main')
    op.drop_table('recipe_categories', schema='main')
    op.drop_index('ix_mapping_logs_ingredient_id', table_name='mapping_logs', schema='main')
    op.drop_table('mapping_logs', schema='main')
    op.drop_index('ix_mapped_ingredient_values_primary_id', table_name='mapped_ingredient_values', schema='main')
    op.drop_index('ix_mapped_ingredient_values_ingredient_id', table_name='mapped_ingredient_values', schema='main')
    op.drop_index('ix_mapped_ingredient_values_author_id', table_name='mapped_ingredient_values', schema='main')
    op.drop_table('mapped_ingredient_values', schema='main')
    op.drop_index('ix_users_type_id', table_name='users', schema='public')
    op.drop_index('ix_users_login', table_name='users', schema='public')
    op.drop_table('users', schema='public')
    op.drop_index('ix_recipe_ingredients_recipe_id', table_name='recipe_ingredients', schema='public')
    op.drop_index('ix_recipe_ingredients_ingredient_id', table_name='recipe_ingredients', schema='public')
    op.drop_table('recipe_ingredients', schema='public')
    op.drop_index('ix_products_category_id', table_name='products', schema='public')
    op.drop_table('products', schema='public')
    op.drop_index('ix_nutrients_header_id', table_name='nutrients', schema='public')
    op.drop_table('nutrients', schema='public')
    op.drop_index('ix_tagged_ingredient_values_tag_id', table_name='tagged_ingredient_values', schema='main')
    op.drop_index('ix_tagged_ingredient_values_ingredient_id', table_name='tagged_ingredient_values', schema='main')
    op.drop_table('tagged_ingredient_values', schema='main')
    op.drop_index('ix_recipes_unit_volume_id', table_name='recipes', schema='main')
    op.drop_index('ix_recipes_photo_file_id', table_name='recipes', schema='main')
    op.drop_index('ix_recipes_method_id', table_name='recipes', schema='main')
    op.drop_index('ix_recipes_consultant_id', table_name='recipes', schema='main')
    op.drop_table('recipes', schema='main')
    op.drop_index('ix_ingredients_name_consultant_id', table_name='ingredients', schema='main')
    op.drop_index('ix_ingredients_consultant_id', table_name='ingredients', schema='main')
    op.drop_table('ingredients', schema='main')
    op.drop_index('ix_user_types_reference_type', table_name='user_types_reference', schema='public')
    op.drop_table('user_types_reference', schema='public')
    op.drop_table('tags_reference', schema='public')
    op.drop_table('recipes', schema='public')
    op.drop_table('product_list_categories', schema='public')
    op.drop_index('ix_parsing_themes_first_category_second_category', table_name='parsing_themes', schema='public')
    op.drop_index('ix_parsing_themes_filename', table_name='parsing_themes', schema='public')
    op.drop_table('parsing_themes', schema='public')
    op.drop_table('nutrient_list_headers', schema='public')
    op.drop_table('ingredients', schema='public')
    op.drop_table('recipe_list_categories', schema='main')
    op.drop_index('ix_recipe_dish_units_reference_name_type', table_name='recipe_dish_units_reference', schema='main')
    op.drop_table('recipe_dish_units_reference', schema='main')
    op.drop_index('ix_recipe_dish_tags_reference_name', table_name='recipe_dish_tags_reference', schema='main')
    op.drop_table('recipe_dish_tags_reference', schema='main')
    op.drop_index('ix_recipe_dish_preparation_methods_reference_name', table_name='recipe_dish_preparation_methods_reference', schema='main')
    op.drop_table('recipe_dish_preparation_methods_reference', schema='main')
    op.drop_index('ix_primary_ingredients_name', table_name='primary_ingredients', schema='main')
    op.drop_table('primary_ingredients', schema='main')
    op.drop_table('files', schema='main')
    op.drop_index('ix_consultants_id', table_name='consultants', schema='main')
    op.drop_table('consultants', schema='main')
    # ### end Alembic commands ###
