"""add eav tables

Revision ID: d2b7b127874e
Revises: 55c6aaa7a645
Create Date: 2024-01-07 11:55:25.283923

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd2b7b127874e'
down_revision: Union[str, None] = '55c6aaa7a645'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attributes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_table('entities',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_table('values',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_table('parsing_results',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('entity_id', sa.String(), nullable=False),
    sa.Column('attribute_id', sa.String(), nullable=False),
    sa.Column('value_id', sa.String(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['attribute_id'], ['public.attributes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['entity_id'], ['public.entities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['value_id'], ['public.values.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['public.parsing_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('parsing_results', schema='public')
    op.drop_table('values', schema='public')
    op.drop_table('entities', schema='public')
    op.drop_table('attributes', schema='public')
    # ### end Alembic commands ###
