"""fill public tables with data

Revision ID: f43b2b98c3c2
Revises: cc674899ad1a
Create Date: 2023-11-05 01:52:28.047975

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f43b2b98c3c2'
down_revision: Union[str, None] = 'cc674899ad1a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    files = [
        "public-ingredients",
        "public-nutrient-list-headers",
        "public-nutrients",
        "public-parsing-themes",
        "public-product-list-categories",
        "public-products",
        "public-product-nutrients-part1",
        "public-product-nutrients-part2",
        "public-products-ingredients",
        "public-recipes",
        "public-recipe-ingredients",
        "public-tags-reference",
        "public-tags-products",
        "public-user-types-reference",
        "public-users"
    ]

    for file in files:
        with open(f"./alembic/scripts/{file}.sql", "r", encoding="utf-8") as f:
            query = f.read()
        query = query.replace("\n", "")
        op.execute(query)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
